version: '3.9'
services:
  my-app:
    image: fluffypyjamas/todo-server:latest
    ports:
      - "8080:8080"
    depends_on:
      - db
  db:
    image: fluffypyjamas/todo-db:latest
    container_name: todoDB
    environment:
      MYSQL_USER: user
      MYSQL_ROOT_PASSWORD: 123456
      MYSQL_PASSWORD: 123456
      MYSQL_DATABASE: todo
    ports:
      - "3306:3306"